baseURL = 'https://domekbajeczka.pl/'
languageCode = 'pl-PL'
title = 'Domek Bajeczka'

enableRobotsTXT = true
enableEmoji = true


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enables use of <sub> and other html sutff in markdown
      unsafe = true

